chore: POM files
eu-LISA/domibusConnector pull request #14
Opened 2024-04-08 09:15 UTC by komi-eulisa

- reorder properties
- reorder dependencies
- reorder plugins
- set Jfrog artifactory URL
- set by default release and snapshot distribution management URLs
- generate Javadoc by default
- change the version of the Javadoc plugin from 3.0.1 to 3.6.3
- make modules pom files dependencies and plugins depend on those configured in the main POM file

2024-04-08 09:48 UTC, zugazagoitia-eulisa requested changes
Added some comments.

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +        <url>https://github.com/eu-LISA/ecodex-workflows</url>
Replace with `https://github.com/eu-LISA/domibusConnector/actions` since the workflows repo is meant as templates for all ecodex repos

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +        <maven.compiler.source>1.8</maven.compiler.source>
Pull the java versions to the top, out of plugins

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +        if a proxy is used during build or test configure this properties
Let's remove support for this proxy part altogether, do we need it?

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +        <!-- keep this empty properties! -->
We don't need them anymore, does it compile without them? Where are they used?

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +                    <artifactId>maven-site-plugin</artifactId>
What do we use it for?

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +                    <artifactId>build-helper-maven-plugin</artifactId>
What is it used for?

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +                    <artifactId>versions-maven-plugin</artifactId>
Do we need it having IDE and Dependabot visibility?

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +                    <artifactId>fabric8-maven-plugin</artifactId>
We should get rid of this, it is deprecated and any docker/k8s should be independent from maven

2024-04-08 09:48 UTC, zugazagoitia-eulisa commented on pom.xml
> +                <artifactId>openshift-maven-plugin</artifactId>
Same as with the other Kubernetes, no need in Maven

2024-04-08 09:58 UTC, komi-eulisa commented on pom.xml
> +        <url>https://github.com/eu-LISA/ecodex-workflows</url>
Done

2024-04-08 09:59 UTC, komi-eulisa commented on pom.xml
> +        if a proxy is used during build or test configure this properties
Yes we can remove it

2024-04-08 10:00 UTC, komi-eulisa commented on pom.xml
> +        if a proxy is used during build or test configure this properties
Done

2024-04-08 10:04 UTC, komi-eulisa commented on pom.xml
> +                    <artifactId>maven-site-plugin</artifactId>
To generate a site for the project.
https://maven.apache.org/plugins/maven-site-plugin/

2024-04-08 10:14 UTC, zugazagoitia-eulisa commented on pom.xml
> +                    <artifactId>maven-site-plugin</artifactId>
Where is this project site used was my question? Is it part of the distribution?

2024-04-08 10:27 UTC, komi-eulisa commented on pom.xml
> +                    <artifactId>versions-maven-plugin</artifactId>
We can get rid of it

2024-04-08 10:38 UTC, komi-eulisa commented on pom.xml
> +                    <artifactId>versions-maven-plugin</artifactId>
Removed

2024-04-08 10:42 UTC, komi-eulisa commented on pom.xml
> +                <artifactId>openshift-maven-plugin</artifactId>
We need to remove the domibusConnectorBuilder module then, as it depends on it.
Do you think it is OK to remove it from this branch?

2024-04-08 11:37 UTC, komi-eulisa commented on pom.xml
> +        <maven.compiler.source>1.8</maven.compiler.source>
Done

2024-04-08 11:49 UTC, komi-eulisa commented on pom.xml
> +        <!-- keep this empty properties! -->
Yes it does

2024-04-08 11:50 UTC, komi-eulisa commented on pom.xml
> +        <!-- keep this empty properties! -->
Removed

2024-04-08 12:16 UTC, komi-eulisa commented on pom.xml
> +                    <artifactId>fabric8-maven-plugin</artifactId>
Removed

2024-04-08 12:29 UTC, komi-eulisa commented on pom.xml
> +                    <artifactId>build-helper-maven-plugin</artifactId>
seems no longer used

2024-04-08 12:29 UTC, komi-eulisa commented on pom.xml
> +                    <artifactId>build-helper-maven-plugin</artifactId>
Removed

2024-04-08 14:19 UTC, zugazagoitia-eulisa commented on pom.xml
> +                <artifactId>openshift-maven-plugin</artifactId>
Let's create an issue about it and not do it now

2024-04-09 06:52 UTC, zugazagoitia-eulisa approved these changes

2024-04-09 06:52 UTC, merged